-- Jovick Dine Delivery: public read-only menu catalogue.
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null check (category in ('Rice', 'Swallow', 'Grills', 'Everyday', 'Soups', 'Sides')),
  price integer not null check (price > 0),
  rating numeric(2,1) not null default 4.7 check (rating >= 0 and rating <= 5),
  tag text not null default 'House favourite',
  description text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.menu_items enable row level security;
revoke all on table public.menu_items from public, anon, authenticated;
grant select on table public.menu_items to anon, authenticated;
drop policy if exists "Anyone can read available menu items" on public.menu_items;
create policy "Anyone can read available menu items"
  on public.menu_items for select
  to anon, authenticated
  using (is_available = true);

insert into public.menu_items
  (slug, name, category, price, rating, tag, description, image_url, is_available, sort_order)
values
  ('jollof-rice-grilled-chicken', 'Jollof Rice & Grilled Chicken', 'Rice', 6500, 4.9, 'Customer favourite', 'Smoky party-style jollof, juicy grilled chicken and plantain.', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=85', true, 1),
  ('egusi-pounded-yam', 'Egusi & Pounded Yam', 'Swallow', 5500, 4.8, 'Local classic', 'Rich melon-seed soup with assorted meat and soft pounded yam.', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85', true, 2),
  ('suya-beef-bowl', 'Suya Beef Bowl', 'Grills', 4800, 4.8, 'Spicy & smoky', 'Char-grilled beef suya, onions, fresh tomatoes and pepper sauce.', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85', true, 3),
  ('ofada-rice-ayamase', 'Ofada Rice & Ayamase', 'Rice', 6200, 4.9, 'House special', 'Local ofada rice with bold green pepper sauce and assorted meat.', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85', true, 4),
  ('peppered-chicken-wings', 'Peppered Chicken Wings', 'Grills', 5200, 4.7, 'Crowd pleaser', 'Crispy wings tossed in a sweet, savoury Nigerian pepper glaze.', 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=85', true, 5),
  ('beans-fried-plantain', 'Beans & Fried Plantain', 'Everyday', 3200, 4.7, 'Comfort food', 'Slow-cooked beans served with golden ripe plantain.', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85', true, 6),
  ('yam-egg-sauce', 'Yam & Egg Sauce', 'Everyday', 2800, 4.6, 'Breakfast pick', 'Soft boiled yam with fresh tomato, pepper and egg sauce.', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=85', true, 7),
  ('catfish-pepper-soup', 'Catfish Pepper Soup', 'Soups', 7000, 4.8, 'Weekend favourite', 'Fragrant, warming pepper soup with fresh catfish and herbs.', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85', true, 8),
  ('puff-puff-six', 'Puff-Puff (6 pieces)', 'Sides', 1500, 4.6, 'Sweet treat', 'Freshly fried golden puff-puff, light on the inside.', 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=900&q=85', true, 9)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  rating = excluded.rating,
  tag = excluded.tag,
  description = excluded.description,
  image_url = excluded.image_url,
  is_available = excluded.is_available,
  sort_order = excluded.sort_order,
  updated_at = now();
